<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitad2e9eae8b2b4c78e6566576e7c4c127
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('PopupMaker\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \PopupMaker\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInitad2e9eae8b2b4c78e6566576e7c4c127', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \PopupMaker\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitad2e9eae8b2b4c78e6566576e7c4c127', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\PopupMaker\Vendor\Composer\Autoload\ComposerStaticInitad2e9eae8b2b4c78e6566576e7c4c127::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
